import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const isTabletLike = width >= 768;

const COLORS = {
  background: "#1f1f1f",
  surfacePrimary: "#2a2f36",
  surfaceSecondary: "#313842",
  surfaceAccent: "#5d6976",
  borderStrong: "rgba(255,255,255,0.30)",
  borderSoft: "rgba(255,255,255,0.12)",
  textPrimary: "#f3f4f6",
  textSecondary: "#aeb4bd",
  textMuted: "#8f98a3",
  danger: "#ff8c96",
  overlay: "rgba(0,0,0,0.52)",
};

export const styles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    backgroundColor: COLORS.background,
    paddingHorizontal: isTabletLike ? 32 : 20,
    paddingTop: isTabletLike ? 40 : 28,
    paddingBottom: 28,
  },
  container: {
    width: "100%",
    maxWidth: 720,
    alignSelf: "center",
  },
  headerBlock: {
    marginBottom: 22,
  },
  heading: {
    fontSize: isTabletLike ? 30 : 26,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.textSecondary,
    maxWidth: 560,
  },
  topSpacer: {
    marginTop: 12,
  },
  noticeCard: {
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: 18,
    borderWidth: 0.3,
    borderColor: COLORS.borderSoft,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  noticeText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  statusBlock: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  statusText: {
    marginLeft: 10,
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  errorText: {
    color: COLORS.danger,
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 16,
  },
  section: {
    marginTop: 16,
  },
  formCard: {
    backgroundColor: COLORS.surfacePrimary,
    borderRadius: 24,
    borderWidth: 0.3,
    borderColor: COLORS.borderStrong,
    paddingHorizontal: isTabletLike ? 28 : 20,
    paddingVertical: isTabletLike ? 28 : 22,
    marginBottom: 18,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: isTabletLike ? 8 : 7 },
    shadowOpacity: 0.18,
    shadowRadius: isTabletLike ? 12 : 10,
    elevation: 3,
  },
  sectionHeader: {
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 6,
  },
  sectionDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  emptyCard: {
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: 16,
    borderWidth: 0.3,
    borderColor: COLORS.borderSoft,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  emptyText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  questionCard: {
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: 18,
    borderWidth: 0.3,
    borderColor: COLORS.borderSoft,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 14,
  },
  questionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textMuted,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  questionText: {
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.textPrimary,
  },
  answerRow: {
    flexDirection: "row",
    marginTop: 14,
  },
  answerButton: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.3,
  },
  answerButtonSpacing: {
    marginRight: 8,
  },
  answerButtonActive: {
    backgroundColor: COLORS.surfaceAccent,
    borderColor: COLORS.borderStrong,
  },
  answerButtonInactive: {
    backgroundColor: COLORS.background,
    borderColor: COLORS.borderSoft,
  },
  answerText: {
    fontWeight: "600",
    fontSize: 14,
  },
  answerTextActive: {
    color: COLORS.textPrimary,
  },
  answerTextInactive: {
    color: COLORS.textSecondary,
  },
  submitError: {
    color: COLORS.danger,
    marginTop: 8,
    fontSize: 14,
    fontWeight: "500",
  },
  actionButton: {
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.3,
    minHeight: 52,
  },
  actionButtonTopSpacing: {
    marginTop: 12,
  },
  actionButtonActive: {
    backgroundColor: COLORS.surfaceAccent,
    borderColor: COLORS.borderStrong,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 3,
  },
  actionButtonDisabled: {
    backgroundColor: "#4a525d",
    borderColor: COLORS.borderSoft,
    opacity: 0.72,
  },
  actionButtonText: {
    color: COLORS.textPrimary,
    fontWeight: "600",
    fontSize: 15,
  },
  mutedText: {
    color: COLORS.textMuted,
    marginBottom: 8,
    fontSize: 14,
    lineHeight: 20,
  },
  uploadError: {
    color: COLORS.danger,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: "500",
  },
  infoCard: {
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: 18,
    borderWidth: 0.3,
    borderColor: COLORS.borderSoft,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 14,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 6,
  },
  infoText: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    backgroundColor: COLORS.surfacePrimary,
    borderRadius: 20,
    padding: 20,
    width: "100%",
    maxWidth: 320,
    alignItems: "center",
    borderWidth: 0.3,
    borderColor: COLORS.borderStrong,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  modalBody: {
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 16,
    fontSize: 14,
    lineHeight: 21,
  },
  modalButton: {
    backgroundColor: COLORS.surfaceAccent,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 0.3,
    borderColor: COLORS.borderStrong,
    minWidth: 160,
    alignItems: "center",
    justifyContent: "center",
  },
});